### PR TITLE
Update the import paths for Caddy

### PR DESCRIPTION
**Pull request by whalehub**
This pull request makes caddy-builder compatible with Caddy v1.0.1+ (see epicagency/caddy-expires#6 for reference) by updating the import paths for Caddy.

### CODE REVIEW

**Comment by alexellis** [comment]
This commit looks right now.

Please can you check the CI failure? https://travis-ci.org/openfaas/caddy-builder/builds/556225009?utm_source=github_status&utm_medium=notification

**Comment by alexellis** [comment]
Change looks good, but it's still failing. Can you check the logs again?

Alex

**Comment by alexellis** [comment]
Have you tried running the steps from .travis.yml on your local PC?

**Comment by alexellis** [comment]
@whalehub please can you try running on your own machine before pushing?

**Comment by whalehub** [comment]
@alexellis That's the thing, it works fine on my machine. Any ideas why it keeps saying "permission denied" even though I've tried applying the execute permission to the binary in three different ways?

**Comment by whalehub** [comment]
@alexellis The actual build process of Caddy always finishes successfully since I pushed https://github.com/openfaas/caddy-builder/pull/4/commits/9fc86577fda804c540763bb9b107709d4b98797e; it's the verification of the installed plugins with `/usr/bin/caddy -plugins` at the end that fails because of a "permission denied" error. As you can see in [the latest Travis CI build](https://travis-ci.org/openfaas/caddy-builder/builds/556258166?utm_source=github_status&utm_medium=notification), Caddy does have execute permissions across the board, so this error makes no sense to me.

```
Step 11/18 : RUN chmod +x /usr/bin/caddy && cd /usr/bin && ls -al
 ---> Running in be56aefd5412
total 460
drwxr-xr-x    1 root     root          4096 Jul  9 11:37 .
drwxr-xr-x    1 root     root          4096 Jun 19 17:14 ..
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 [ -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 [[ -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 awk -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 basename -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 bc -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 beep -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 blkdiscard -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 bunzip2 -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 bzcat -> /bin/busybox
lrwxrwxrwx    1 root     root            12 Jun 19 17:14 bzip2 -> /bin/busybox
-rwxr-xr-x    1 root     root         14208 May  3 11:54 c_rehash
drwxr-xr-x    1 root     root          4096 Jul  9 11:37 caddy
```
```
Step 12/18 : RUN /usr/bin/caddy -plugins
 ---> Running in 41d8256450b6
/bin/sh: /usr/bin/caddy: Permission denied
```

**Comment by whalehub** [comment]
@alexellis The Travis build finally finished successfully! Basically, the build process you used in your Dockerfile was outdated and had to be updated to be compatible with Go modules, which were introduced with Caddy 1.0.0 back in April this year. I'll make another commit to update the documentation in your repository and then you should be good to go with merging this pull request.

**Side note:** I had to remove the Prometheus plugin from the build process because its author has not yet pushed a new release ever since he fixed the import paths for Caddy. I posted a request on his GitHub repository about that, but until then, the only way to build Caddy with that plugin is to specify the hash of the latest commit in the `go.mod` file. I'll also add a note about that in the documentation.

**Comment by alexellis** [comment]
Did you get there? :-)

**Comment by whalehub** [comment]
@alexellis Yeah, I'm done now.

**Comment by alexellis** [comment]
Please could you squash your commits into one?

Thank you for your hard work. 

It would also be good to get a link back to the issue that you raised on the Prometheus plugin.

**Comment by whalehub** [comment]
@alexellis I opened a new pull request with only one commit just now. I have also included Prometheus in the `go.mod` and the `README.md` file again because its developer updated the plugin to be compatible with Caddy v1.0.1 yesterday.

**Pull request closed without merging**
