### PR TITLE
Update the import paths for Caddy

### PR DESCRIPTION
**Pull request by whalehub**
This pull request makes caddy-builder compatible with Caddy v1.0.1+ (see epicagency/caddy-expires#6 for reference) by updating the import paths for Caddy.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for your pull request. Please can I ask you to sign off this commit?

```
git commit --signoff --amend
```

**Comment by whalehub** [comment]
@alexellis This is the first time I signed off a commit, hope I did everything correctly!

**Comment by alexellis** [comment]
The commit is signed-off now, but I am not sure why you then did a merge commit? It seems unnecessary, especially since you are the only one making changes.

Please can you reset your changes and apply them in a single commit which is also signed-off?

Try something like:

```
git reset HEAD~2
git add .
git commit --signoff
```

Followed by a force push.

Alex

**Comment by whalehub** [comment]
I'm using GitHub Desktop so I'm not sure how those commands translate to it. I'm just going to open a new pull request with the same changes and sign it.

**Comment by alexellis** [comment]
Thank you 👍

**Pull request closed without merging**
