### PR TITLE
Update the import paths for Caddy

### PR DESCRIPTION
**Pull request by whalehub**
This pull request makes caddy-builder compatible with Caddy v1.0.1+ (see epicagency/caddy-expires#6 for reference) by updating the import paths for Caddy and by updating the build process to be compatible with Go modules (required for building Caddy v1.0.0+ from source)

### CODE REVIEW

**Comment by whalehub** [comment]
@alexellis Could you please have a look at this revised PR?

**Comment by alexellis** [comment]
I've merged. 

For future commits, please include your whole name as per the contributing guide.

Alex

**Comment by alexellis** [comment]
I've made a release 0.1.0 - let me know if it worked as expected.

Alex

**Comment by whalehub** [comment]
@alexellis Thanks, everything is working as expected.

**Pull request merged**
